server:
  port: 10081
  servlet:
    context-path: /${artifactId}

dubbo:
  application:
    name: ${artifactId}
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
  protocol:
    serialization: kryo

swagger:
  enabled: true
  print-init: true
  docket:
    base-package: com.cn.boot.sample.business.controller
    group-name: ${artifactId}
    path-selectors:
      exclude-patterns: [/error]
    api-info:
      contact:
        name: ChenNan
        email: 327919006@qq.com
        url: https://gitee.com/NuLiing
      title: ${artifactId}
      description: ${artifactId}-接口文档
      license: Apache License, Version 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: ${project.version}
      terms-of-service-url: https://gitee.com/NuLiing
    response-message-language: cn

spring:
  task:
    execution:
      thread-name-prefix: myExecute-
      pool:
        max-size: 100

test:
  config:
    address: 北京
    users:
      - name: user1
        age: 11
      - name: user2
        age: 22