server:
  port: 10086
  servlet:
    context-path: /${artifactId}

wechat:
  token: 123456
  app-id: wx53c809c42dcddfc4
  app-secret: 5a081261e1ab15b32665de21083c44a9

swagger:
  enabled: true
  print-init: true
  docket:
    base-package: com.cn.boot.sample.wechat.controller
    group-name: ${artifactId}
    path-selectors:
      exclude-patterns: [/error]
    api-info:
      contact:
        name: ChenNan
        email: 327919006@qq.com
        url: https://gitee.com/NuLiing
      title: ${artifactId}
      description: ${artifactId}-接口文档
      license: Apache License, Version 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: ${project.version}
      terms-of-service-url: https://gitee.com/NuLiing
    response-message-language: cn
