# 开发环境配置
server:
  port: 10084


spring:
  datasource:
    druid:
      db1:
        #注意：如果使用druid数据库连接池，配置为url，如果是默认的hikari，要配置jdbc-url
        url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: chennan
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        min-idle: 5
        max-active: 10
        max-wait: 60000
      db2:
        url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: chennan
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        min-idle: 5
        max-active: 10
        max-wait: 60000



# Dubbo配置
dubbo:
  application:
    name: ${artifactId}
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.cn.boot.sample.server.more.service
