server:
  port: 10093
  servlet:
    context-path: /${artifactId}
  config: '{"servers":{"S3":{"appTags":[{"name":"APP1","weight":10,"areaTags":[{"name":"区服1","weight":20}]}],"maxConnect":50000,"maxCpu":80.0,"serverUri":"218.104.231.103"},"S4":{"appTags":[{"name":"APP1","weight":10,"areaTags":[{"name":"区服2","weight":20},{"name":"区服3","weight":20},{"name":"区服4","weight":20}]}],"maxConnect":50000,"maxCpu":80.0,"serverUri":"218.104.231.104"},"S5":{"appTags":[{"name":"APP2","weight":10}],"maxConnect":50000,"maxCpu":80.0,"serverUri":"218.104.231.105"},"S6":{"appTags":[{"name":"APP3","weight":10},{"name":"APP4","weight":10},{"name":"APP5","weight":10}],"maxConnect":50000,"maxCpu":80.0,"serverUri":"218.104.231.106"},"PC-20190610KWVD":{"appTags":[{"name":"APP1","weight":10,"areaTags":[{"name":"区服1","weight":20}]}],"maxConnect":100000,"maxCpu":80.0,"serverUri":"127.0.0.1"},"S2":{"appTags":[{"name":"APP1","weight":10}],"maxConnect":50000,"maxCpu":80.0,"serverUri":"218.104.231.102"}},"serverPort":1899,"parentNode":"/test/dev","loadRule":{"cpu":{"step":10.0,"weight":-1},"connect":{"step":10.0,"weight":-1}}}'

zookeeper:
  uri: 127.0.0.1:2181

swagger:
  enabled: true
  print-init: true
  docket:
    base-package: com.cn.boot.sample.zookeeper.controller
    group-name: ${artifactId}
    path-selectors:
      exclude-patterns: [/error]
    api-info:
      contact:
        name: ChenNan
        email: 327919006@qq.com
        url: https://gitee.com/NuLiing
      title: ${artifactId}
      description: ${artifactId}-接口文档
      license: Apache License, Version 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: ${project.version}
      terms-of-service-url: https://gitee.com/NuLiing
    response-message-language: cn
