spring:
  profiles:
    active: @profileActive@


mybatis:
  typeAliasesPackage: com.cn.boot.sample.api.model.po
  mapperLocations: classpath:com/cn/boot/sample/dal/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true